USE co2;

INSERT INTO pais(codigo_iso,pais)
SELECT DISTINCT codigo_iso,pais FROM intensidad_electricidad;
-- ALTER TABLE pais DROP COLUMN Id_pais;
ALTER TABLE pais ADD COLUMN Id_pais 
INT NOT NULL PRIMARY KEY AUTO_INCREMENT FIRST;

DELETE p1 from pais p1
INNER JOIN pais p2
WHERE p1.Id_pais<p2.Id_pais AND p1.pais=p2.pais;
SELECT * FROM pais;


ALTER TABLE acceso_electricidad ADD COLUMN Id_ae
INT NOT NULL PRIMARY KEY AUTO_INCREMENT FIRST;

ALTER TABLE cancer_pulmon ADD COLUMN Id_cp
INT NOT NULL PRIMARY KEY AUTO_INCREMENT FIRST;

ALTER TABLE central_electrica ADD COLUMN Id_ce
INT NOT NULL PRIMARY KEY AUTO_INCREMENT FIRST;

ALTER TABLE climate_disasters ADD COLUMN Id_cd
INT NOT NULL PRIMARY KEY AUTO_INCREMENT FIRST;

ALTER TABLE data_er ADD COLUMN Id_der
INT NOT NULL PRIMARY KEY AUTO_INCREMENT FIRST;

ALTER TABLE energyco2 ADD COLUMN Id_eco
INT NOT NULL PRIMARY KEY AUTO_INCREMENT FIRST;
