name: py

on:
  push:
    branches: ["dev"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup jupter
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
      - name: Install dependencies 
        run: |
            python -m pip install --upgrade pip
            pip install pandas plotly numpy jupyter jupyterlab
      - name: execute jupyterlab
        run: jupyter lab --NotebookApp.token=123
