version: 3.9

services:
  web:
    build: nginx
    ports:
      - 80:80
      - 433:433
    depends_on:
      - api

  api:
    build: domainchecker
    enviroment:
      - PORT=8080
    ports:
      - 8080:8080
